version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: my_api_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ale@@
      POSTGRES_DB: db_produtos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_api_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ale@teste.com
      PGADMIN_DEFAULT_PASSWORD: ale@030303
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: